clc;
E_mag=input("Input the magnitude value of synchronous generator voltage, E_mag = ");
V=input("Input the infinite bus terminal voltage value, V = ");
Pe=input("Input the real power of synchronous generator value, Pe = ");
XL1=input("Input the line1 reactance value, XL1 = ");
XL2=input("Input the line2 reactance value, XL2 = ");
xx=input("Input the synchronous generator reactance value, xx = ");

%Prefault condition
Pm=Pe;
X1=xx+((XL1)*(XL2)/(XL1+XL2));  %equivalent reactance before fault
P1max=(E_mag*abs(V))/abs(X1);   %max value of power delivered by generator in prefault condition
delta_0=asin(Pm/P1max);          %initial operating rotor angle del_0

%During fault condition
P2=0;

%After fault(line 2 outage)
X3=xx + XL1;  %equivalent reactance after fault
P3max=(E_mag*abs(V))/abs(X3);  %max value of power delivered by generator in after fault condition

delta_max=pi-asin(Pm/P3max);
delta_cr=acos((((delta_max-delta_0)*Pm)+P3max*cos(delta_max))/P3max);
fprintf('Critical clearing rotor angle = %.4f',delta_cr);


yy=[0,Pm,Pm,0];
delta=linspace(0,pi,100);
P1=P1max*sin(delta);
P3=P3max*sin(delta);
plot(delta,P1,delta,P2,delta,P3)
hold on
yline(Pm);
xx=[delta_0,delta_0,delta_cr,delta_cr];
patch(xx,yy,'red')
hold on
basevalue=Pm;
delta_00=linspace(delta_cr,delta_max,10);
yyy=P3max*sin(delta_00);
area(delta_00,yyy,basevalue);
legend('P1','P2','P3','Pm');
xlabel('delta(rad)');
ylabel('Power generated by sync generator');
title('P-del curve');